export const GET_SHIFTS_REQUESTED = 'GET_SHIFTS_REQUESTED';
export const GET_SHIFTS_SUCCESS = 'GET_SHIFTS_SUCCESS';
export const GET_SHIFTS_FAILED = 'GET_SHIFTS_FAILED';

export const ADD_REQ_SHIFT_REQUESTED = 'ADD_REQ_SHIFT_REQUESTED';
export const ADD_REQ_SHIFT_SUCCESS = 'ADD_REQ_SHIFT_SUCCESS';
export const ADD_REQ_SHIFT_FAILED = 'ADD_REQ_SHIFT_FAILED';

export const GET_USERS_REQUESTED = 'GET_USERS_REQUESTED';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILED = 'GET_USERS_FAILED';

export const GET_SUB_SHIFTS_REQUESTED = 'GET_SUB_SHIFTS_REQUESTED';
export const GET_SUB_SHIFTS_SUCCESS = 'GET_SUB_SHIFTS_SUCCESS';
export const GET_SUB_SHIFTS_FAILED = 'GET_SUB_SHIFTS_FAILED';

export const GET_SCHEDULED_SHIFTS_REQUESTED = 'GET_SCHEDULED_SHIFTS_REQUESTED'
export const GET_SCHEDULED_SHIFTS_SUCCESS = 'GET_SCHEDULED_SHIFTS_SUCCESS'
export const GET_SCHEDULED_SHIFTS_FAILED = 'GET_SCHEDULED_SHIFTS_FAILED'

export const ADD_SCHEDULED_SHIFTS_REQUESTED = 'ADD_SCHEDULED_SHIFTS_REQUESTED'
export const ADD_SCHEDULED_SHIFTS_SUCCESS = 'ADD_SCHEDULED_SHIFTS_SUCCESS'
export const ADD_SCHEDULED_SHIFTS_FAILED = 'ADD_SCHEDULED_SHIFTS_FAILED'